// flow-typed signature: 3c8d2ae773007aa6a98e30c14ba8ed1f
// flow-typed version: <<STUB>>/rapidapi-connect_v0.0.6/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rapidapi-connect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rapidapi-connect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rapidapi-connect/socket' {
  declare module.exports: any;
}

declare module 'rapidapi-connect/test/rapidapi' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rapidapi-connect/index' {
  declare module.exports: $Exports<'rapidapi-connect'>;
}
declare module 'rapidapi-connect/index.js' {
  declare module.exports: $Exports<'rapidapi-connect'>;
}
declare module 'rapidapi-connect/socket.js' {
  declare module.exports: $Exports<'rapidapi-connect/socket'>;
}
declare module 'rapidapi-connect/test/rapidapi.js' {
  declare module.exports: $Exports<'rapidapi-connect/test/rapidapi'>;
}
