// flow-typed signature: ab213de6d6b0f2ad5a684d5f4cde6f27
// flow-typed version: <<STUB>>/serverless-plugin-optimize_v^3.1.1-rc.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless-plugin-optimize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless-plugin-optimize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serverless-plugin-optimize/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serverless-plugin-optimize/src/index.js' {
  declare module.exports: $Exports<'serverless-plugin-optimize/src/index'>;
}
